### ISSUE TITLE
Installed as per the README but nothing happens?

### ISSUE THREAD

**Issue by vitobotta** [olegsu/iris#44]
Hi! I just installed Iris with Helm, and am trying to use it with a little service as destination which just prints out the even data for now. The service itself works, but when I create/delete pods etc in the default namespace, nothing happens. I am using the same configuration as in the README apart from the URL of the service, which is in the format `http://<service name>.<service ns>.svc.cluster.local`.  I also don't see anything in Iris' logs apart from the startup messages.

What can I do? Thanks! :)

**Comment by vitobotta** [comment]
I forgot to mention that the container didn't start at first, complaining about the kubeconfig. So I am using now the --in-cluster argument as per https://github.com/olegsu/iris/issues/34 and the pod starts now.

**Comment by vitobotta** [comment]
It looks like it's a problem when installing with helm... I made the changes to the deployment following [this](https://github.com/olegsu/iris/issues/39) and I see some activity in the logs, although it's not firing a request to my service yet...

**Comment by vitobotta** [comment]
Got it working, I had forgotten to specify the port in the URL.

**Comment by vitobotta** [comment]
I spoke too soon... everything works with the default namespace, but I am trying to watch events in the velero namespace - my ultimate goal is to get slack notifications of backups. If I just change the namespace nothing happens. Any idea?

**Comment by olegsu** [comment]
Thanks @vitobotta for the report.
I'm not able to check into this before the 3rd of November. 
Will update once have any news.
